- modules/actionbar.lua
Fixed the Shapeshift-Actionbar overlapping the Pet-Actionbar on Warriors & Druids (Classes with Shapeshift forms).
When these classes acquire a pet (for example controlling Razorgore the Untamed in Blackwing Lair) their Shapeshift-Buttons wont let them click on the destroy egg action on Razorgores Actionbar .
> Warrior & Druid Pet Fix

- modules/mirrortimers.lua
- modules/thirdparty.lua
- modules/unlock.lua
Pretty debatable unlock change. Should only substring the frame label name if starts with pf. This allows blizzard frames and other non pf frames to be able to be movables and have the label show correctly.
> mirrortimers: make them movable

- api/unitframes.lua
Unending Breath
Detect Greater Invisibility
Detect Invisibility
Detect Lesser Invisibility
Paranoia
question: somehow you can do a check of the buff not only on the icon, but also on the name? Because suddenly the player will have a buff that has an similar icon with another buff from the ones specified in the addon and this will cause a false triggering.
Example in PR: Detect Greater Invisibility and Detect Invisibility spells.
> Added support for more warlock spells in group frames

- modules/panel.lua
When player selects to display **XP Percentage** for a panel slot, there is non critical division by zero.
This PR fixes it.
> panel: exp: fixed division by zero on level up

- api/api.lua
- modules/map.lua
Hello.
Right now map doesnt save its state, when you scale or change transparency. Also there is a small non critical error, when you scale to very low value, you get
**This PR is made in 2 commits:**
1) extends **api**, by adding clamp function (its documented)
2) changes in **map**:
- default scale 0.7, alpha 1.0 (just like it was before)
- alpha clamped between 0.1 and 1.0 (0.0 is completely legit, but i don't know if its good idea to let it have, please change if needed)
- scale limited (clamped) between 0.1 and 2.0 (also, up to you to change)
> Map save state

- modules/loot.lua
loot: Inject the banker and disenchanter entries to another couple relevant UnitPopup menus.  
Fix the unitpopup conditional hide so it actually works and those options do not display when not relevant.
Closes #791
> loot: Fix Set Banker and Disenchanter UnitPopup entries.

- api/api.lua
- api/unitframes.lua
api: Prevent race condition in table wipe. Fixes masterlooter random and raidroll options.
unitframes: Fix raid unitpopup menu for 3rd party addons. Fixes set banker, disenchanter options.
> Table Wipe fix and RAID UnitPopup_Menu improvement

- api/api.lua
- modules/actionbar.lua
actionbars: Adjust layout size for dynamically spawned buttons. Fixes issues with shapeshift bar.
It makes it so the config option remains for the max possible buttons for each kind of bar, but it is now possible to shrink the layout to the minimum container the actual buttons spawned need to draw in.
> Fix invalid layout sizes for ShapeshiftBar.

- api/unitframes.lua
correctly sets the Orientation of the Unitframes back to Horizontal
after changing it from vertical
> Fixes #857 - Unitframes Vertical/Horizontal SetOrientation

- modules/focus.lua
Upon UI reload, the `pfUI.uf.focus` frame did not show up until /focus was used a second time. This seems to fix that.
> focus: fix ordering so initial focus is actually shown

- api/unitframes.lua
- modules/durability.lua
- pfUI.toc
I've created a module to make the DurabilityFrame moveable for enhancement request #854 .
I'd suggest making another parameter in the options menu like "Show Durability Frame" so that the user can select to hide the frame entirely. This could maybe be positioned at the options menu for the Minimap? I didn't want to make these adjustments without your input, maybe you have a better idea on where/how to position that.
The Frame itself is positioned by default at the bottom left of the minimap frame, below the "Zone Panel" with estimated the same distance from the frame to the Panel as the Panel has to the Minimap.
> Enhancement #854 - Module 'Durability' to move the Repair/Durability Frame

- api/api.lua
- api/config.lua
- env/translations_deDE.lua
- env/translations_enUS.lua
- env/translations_esES.lua
- env/translations_frFR.lua
- env/translations_koKR.lua
- env/translations_ruRU.lua
- env/translations_zhCN.lua
- env/translations_zhTW.lua
- modules/gui.lua
- modules/loot.lua
**Changelog**  
loot: make detailed random roll announce an option, default: off
api: SendChatMessageWide will use raid warning if player is raid leader or assist
loot: rearrange advanced masterloot menus so random rolling and special recipients precede class menu
loot: fix a special recipients unitpopup menu check so they won't show in the context menu when the player is solo
loot: change the auto confirm bind when solo implementation, so player doesn't have to double-click the loot; also make sure it works if the loot bind confirmation staticpopup is not at index 1
**Comments**  
When I originally put in the random loot assign it was under the assumption that it will be used sparingly and in a PuG setting where announcing the full list of player and assigned number before doing the …
> Various Loot module improvements

- api/api.lua
- modules/panel.lua
Changelog  
api: GetColorGradient method to return a color c between color a and b given a ratio
panel: show damaged items on the repair tooltip with damage breakdown
Comments  
Some of the variables needed to be declared outside of the closure or they get "snapshotted" the first time the function returns [Ref:Closures](https://www.lua.org/pil/6.1.html)  
This also allows us to remove the 2nd loop over the inventory slots to get the repair cost for a small performance optimization.  
Credit to Lichery for starting the discussion with #905
> Implement an item breakdown on repair tooltip

- modules/raid.lua
When you select someone as tank, he will be placed at the beginnig of his group, usefull for heals to see all tank in the same row/column.
> Dropdown option in raid to set a player as tank

- modules/unlock.lua
Example: https://cdn.discordapp.com/attachments/695634717613228043/823649632633749514/unknown.png
You cannot actually edit those boxes. There are 2 things being wrong with it:
1. It awaits an "Escape" button press to modify value, seems counterintuitive, addons like ElvUI do that on Enter press.
2. It does not update values. SetPoint uses previous values, new value is never being used.
This fixes the boxes and mimics the ElvUI behavior for Enter button being the "save" action.
> Fix x and y coord update in frame unlock popup.

- modules/chat.lua
The previous implementation looked like the intention was to use a slightly darker pastel version of the player's class color for the chat tab texts. But the parens around the addition were forgotten, which led to the tab text color bring brighter instead of darker, making it too intrusive.
Before:
After:
> chat: fix tab text color

- modules/actionbar.lua
- modules/hoverbind.lua
Fixes 🐭 #1016 and 🐁 #1127
This extends hoverbind mode to allow binding mouse buttons and mouse wheel up/down to actionbar buttons. It does this by overlaying all actionbar buttons with separate invisible frames that receive all mouse and keyboard events and handle binding creation and removal.
Tested and everything seems to work fine on the following clients:
- 1.12.1 (5875)
- 1.17.1 (7100) (TurtleWoW)
- 2.4.3 (8606)
1. Against my own expectations, I actually managed to make this work somehow... 😄 Thanks again for the ingame support last night @shagu! ❤️
2. Since I'm new to addon development, I'm not sure if this is the most elegant implementation. I'll let you be the judge and I'm looking forward to any kind of feedback.
3. ~~Do we even need the `need_save` variable & logic? The code …
> hoverbind: add support for mouse button & mouse wheel bindings

- libs/libcast.lua
https://github.com/shagu/pfUI/issues/1294
> #1294 [libcast.lua] The "CastSpell" post-hook should set the lastcasttex directly from the return arguments of libspell.GetSpellInfo()

- api/config.lua
- env/translations_deDE.lua
- env/translations_enUS.lua
- env/translations_esES.lua
- env/translations_frFR.lua
- env/translations_koKR.lua
- env/translations_ruRU.lua
- env/translations_zhCN.lua
- env/translations_zhTW.lua
- modules/gui.lua
- modules/mapcolors.lua
Completely rewrote the implementation of the module.
* **Fixed a bug with incorrect class colors determination.**
* Added coloring of nicknames when mouseover on frames. This feature can be disabled in the settings.
* The new implementation does not use OnUpdate all the time.
90% of the time the game is played, there is no need to update this data... Therefore, in the new implementation, the data is updated only when it is really necessary.
Data updating also works on OnUpdate, but now only when the WorldMapFrame and/or BattlefieldMinimap are displayed.
I tested and debugged everything for several days. There shouldn't be any problems
> mapcolors: rewrite module implementation

- libs/libdebuff.lua
The hooks can retrieve the name of the raw-effect from "libspell.GetSpellInfo()". In the case of "CastSpellByName" this will solve a bug which causes debuffs to not be detected optimally in case an explicit rank is passed to "CastSpellByName":
```
/script   CastSpellByName("<some spell>(Rank 2)")
```
> [libdebuff.lua] Align and optimize spell post-hooks

- env/translations_deDE.lua
- env/translations_enUS.lua
- env/translations_esES.lua
- env/translations_frFR.lua
- env/translations_koKR.lua
- env/translations_ruRU.lua
- env/translations_zhCN.lua
- env/translations_zhTW.lua
- modules/panel.lua
The information layout on the gold tooltip makes it hard to quickly add up your total gold across characters with a quick glance.  Added a total line so I didn't have to do the math.  Most of the German translations were set to nil so I added the same, the others are rough machine translations.
> Added total line to gold info panel.  Added (rough) translations.

- libs/libdebuff.lua
- modules/turtle-wow.lua
In 1.17.2 TW devs change Conflagrate. Now it consumes 3 sec Immolate.
You can read new talent description here:
https://talents.turtle-wow.org/warlock
> turtle-wow: update Immolate duration after cast Conflagrate

- modules/turtle-wow.lua
oops sorry. Now work correctly.
> turtle-wow: fix nil error when NPC instantly die from Conflagrate

- modules/gui.lua
- modules/panel.lua
Also changed warlock soulshards to use the item  count in the api
Added a Hearthstone, Thistle Tea, and Flash Powder panel items.
> Fixed up code reduction

- api/unitframes.lua
superwow allows us to use 2nd argument of CastSpellByName to specify spell target unit, this is better than the target + targetlast as it doesnt reset autoattack
> unitframes: use superwow for clickcasting
