shagu/pfUI

- modules/mirrortimers.lua
- pfUI.toc
Preview: 
This is can definitely be improved in the future like making the frames movers and being able to customize them.
Fixes issue: #666
> skin: add mirror timers

- modules/mirrortimers.lua
> mirrortimers: increase bar height and add timer text

- api/config.lua
- env/translations_deDE.lua
- env/translations_enUS.lua
- env/translations_esES.lua
- env/translations_frFR.lua
- env/translations_koKR.lua
- env/translations_ruRU.lua
- env/translations_zhCN.lua
- env/translations_zhTW.lua
- modules/gui.lua
- modules/thirdparty.lua
> thirdparty: add flightmap integration

- modules/panel.lua
Suggested on the [forums](https://forum.elysium-project.org/topic/29034-addon-pfui-an-elvui-inspired-addon-entirely-written-from-scratch/?page=15&tab=comments#comment-442937).
> panel: hide minimap panel if disabled

- modules/skin.lua
> skin: scale the interface options and remove the black background

- api/config.lua
- modules/chat.lua
- modules/gui.lua
> Add Scroll Speed Options

- modules/panel.lua
- pfUI.lua
- pfUI.toc
Shows realm gold of all characters that you have logged in as.
#714
> Panel display account/realm gold

- modules/chat.lua
remove some false positives (eg. 1.1...)
improve some of the existing patterns
add mailto: protocol recognition to email parser
add shorturl support (goo.gl t.co etc)
small refactor to make it possible to process individual capture indexes
> chat: url copy improvements

- api/unitframes.lua
- env/translations_enUS.lua
- env/translations_esES.lua
- env/translations_frFR.lua
- modules/gui.lua
Allow to select short names (3 characters) in unitframes. EN/ES/FR translations added.
> Short Names in unitframes

- modules/autoshift.lua
<https://classic.wowhead.com/spell=24576/chromatic-mount>
<https://classic.wowhead.com/spell=3363/summon-riding-gryphon>
> autoshift: added gryphon (3363) and chromatic drake (24576) mounts

- modules/addonbuttons.lua
https://github.com/shagu/pfUI/issues/1036
> Patched small Cartographer bug

- api/config.lua
- modules/bubbles.lua
- modules/gui.lua
> bubbles: add option to hide borders

- skins/blizzard/character.lua
> character frame: add red quality color for broken items

- libs/libspell.lua
https://github.com/shagu/pfUI/issues/1288
> #1288 make GetSpellInfo() also return the spell-id and book-type

- libs/libspell.lua
https://github.com/shagu/pfUI/issues/1285
> #1285 fix libspell getspellinfo() for ranges and casting-times

- libs/libcast.lua
https://github.com/shagu/pfUI/issues/1296
> #1296 [libcast.lua] make the post-hook of CastSpellByName update the lastcasttex too 

- libs/libcast.lua
- libs/libspell.lua
Something interesting that I noticed is that UnitCastingInfo() returns 'nil' most of the times even when we're casting (at least that's how it behaves in turtle-wow). I left it there for the time being and will re-examine it at some later point.
> #1298 Libcast.lua: Optimize CastCustom() and update hooks accordingly

- modules/chatcopy.lua
https://github.com/shagu/pfUI/issues/1184
> [module] chatcopy - escape from chatcopy mode

- api/unitframes.lua
- libs/libpredict.lua
Added healcomm compatible messaging for Renew, Rejuvenation and Regrowth as well as countdowns to their buff icons on unit frames.
> Add compability with healcomm for vanilla hots.

- modules/thirdparty-vanilla.lua
> skin: improve UnitXP

- api/unitframes.lua
pet happiness only for hunter. localization enabled.
> pet happiness indicator hunter only

- modules/panel.lua
Switched soul shards to count by stack as Turtle, and I assume some others may have them stackable.
> soulshards count stackable
